// <auto-generated />
namespace Library_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddStudentBookIssue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStudentBookIssue));
        
        string IMigrationMetadata.Id
        {
            get { return "202204231413593_AddStudentBookIssue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
